Repository Fluorinebot/fluorine, pull requests merged in 2022-07, with the labels that each got.

#231 prisma
  .env.example
  i18n/en-US.json
  i18n/pl.json
  package-lock.json
  package.json
  prisma/schema.prisma
  src/classes/Client.ts
  src/classes/handlers/ComponentHandler.ts
  src/classes/handlers/CooldownHandler.ts
  src/classes/modules/CasesModule.ts
  src/classes/modules/EconomyModule.ts
  src/classes/modules/ShopModule.ts
  src/commands/balance.ts
  src/commands/ban.ts
  src/commands/case/list.ts
  src/commands/case/view.ts
  src/commands/config/antibot-action.ts
  src/commands/config/antibot.ts
  src/commands/config/currency.ts
  src/commands/config/logs-channel.ts
  src/commands/config/logs.ts
  src/commands/config/mod-logs.ts
  src/commands/config/prefix.ts
  src/commands/deploy/create.ts
  src/commands/deploy/delete.ts
  src/commands/deposit.ts
  src/commands/dev/sql.ts
  src/commands/kick.ts
  src/commands/profile/set.ts
  src/commands/profile/view.ts
  src/commands/rob.ts
  src/commands/shop/buy.ts
  src/commands/shop/create.ts
  src/commands/shop/delete.ts
  src/commands/timeout.ts
  src/commands/warn.ts
  src/commands/withdraw.ts
  src/components/listcase.ts
  src/context/list-cases.ts
  src/events/guildCreate.ts
  src/events/messageCreate.ts
  src/events/messageDelete.ts
  src/events/messageUpdate.ts
  src/events/ready.ts
  src/types/databaseTables.ts
  src/types/structures.ts
Labels: refactor, semver-patch

#248 remove message commands
  i18n/en-US.json
  i18n/pl.json
  src/classes/Client.ts
  src/classes/handlers/ApplicationCommandHandler.ts
  src/classes/handlers/CommandHandler.ts
  src/cmds/8ball.ts
  src/cmds/avatar.ts
  src/cmds/bedwars.ts
  src/cmds/birb.ts
  src/cmds/cat.ts
  src/cmds/dev.ts
  src/cmds/dog.ts
  src/cmds/help.ts
  src/cmds/howgay.ts
  src/cmds/inpost.ts
  src/cmds/ping.ts
  src/cmds/serverinfo.ts
  src/cmds/skywars.ts
  src/commands/deploy/create.ts
  src/commands/deploy/delete.ts
  src/commands/dev/reload.ts
  src/commands/dev/shell.ts
  src/commands/dev/sql.ts
  src/commands/help.ts
  src/components/help.ts
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/types/command.ts
  src/util/info.ts
Labels: refactor, semver-patch

#269 only run ci on main or pull requests
  .github/workflows/test.yml
Labels: ci

#273 remove useless intents
  src/classes/Client.ts
Labels: refactor, semver-patch

#274 partially add string length
  i18n/en-US.json
  i18n/pl.json
  src/classes/Client.ts
  src/commands/ai.ts
  src/commands/ban.ts
  src/commands/kick.ts
  src/commands/shop/create.ts
  src/commands/timeout.ts
  src/commands/warn.ts
Labels: feature, semver-minor

#281 remove explicit usage of `@discordjs/rest`
  .eslintrc.json
  package-lock.json
  package.json
  src/classes/Client.ts
  src/events/interactionCreate.ts
Labels: refactor, dependencies

#283 remove `restModule`
  src/classes/Client.ts
  src/commands/deploy/create.ts
  src/commands/deploy/delete.ts
  src/events/ready.ts
Labels: refactor, semver-patch
