Repository Fluorinebot/fluorine, pull requests merged in 2022-02, with the labels that each got.

#103 remove const help from old cmds
  src/cmds/8ball.ts
  src/cmds/ai.ts
  src/cmds/avatar.ts
  src/cmds/ban.ts
  src/cmds/bedwars.ts
  src/cmds/birb.ts
  src/cmds/case.ts
  src/cmds/cat.ts
  src/cmds/dev.ts
  src/cmds/dog.ts
  src/cmds/help.ts
  src/cmds/howgay.ts
  src/cmds/kick.ts
  src/cmds/mute.ts
  src/cmds/ping.ts
  src/cmds/profile.ts
  src/cmds/serverinfo.ts
  src/cmds/skywars.ts
  src/cmds/stats.ts
  src/cmds/unmute.ts
  src/cmds/update.ts
  src/cmds/warn.ts
Labels: refactor, semver-patch

#106 fix profile choices not being in the right option
  src/commands/profile/index.ts
  src/commands/profile/set.ts
Labels: semver-patch, fix

#108 better ai
  i18n/en-US.json
  i18n/pl.json
  src/classes/AI.ts
  src/classes/Client.ts
  src/cmds/ai.ts
  src/commands/ai.ts
  src/context/ai.ts
Labels: feature, semver-minor

#111 import dapi types from `discord-api-types/v9`
  src/commands/config/index.ts
  src/context/ai.ts
  src/context/avatar.ts
  src/context/howgay.ts
  src/context/listcase.ts
Labels: chore, semver-patch
