Repository Fluorinebot/fluorine, pull requests merged in 2022-03, with the labels that each got.

#119 client cleanup
  i18n/en-US.json
  i18n/pl.json
  package.json
  src/classes/AI.ts
  src/classes/Client.ts
  src/classes/Embed.ts
  src/classes/Logger.ts
  src/classes/handlers/ApplicationCommandHandler.ts
  src/classes/handlers/CommandHandler.ts
  src/classes/handlers/ComponentHandler.ts
  src/classes/handlers/EventHandler.ts
  src/commands/ai.ts
  src/commands/config/antibot-action.ts
  src/commands/config/antibot.ts
  src/commands/config/currency.ts
  src/commands/config/index.ts
  src/commands/config/logs-channel.ts
  src/commands/config/logs.ts
  src/commands/config/mod-logs.ts
  src/commands/config/prefix.ts
  src/commands/deploy/create.ts
  src/commands/deploy/delete.ts
  src/commands/deploy/index.ts
  src/commands/dev/eval.ts
  src/commands/dev/index.ts
  src/commands/dev/reload.ts
  src/commands/dev/shell.ts
  src/commands/dev/update.ts
  src/commands/help.ts
  src/commands/profile/get.ts
  src/commands/profile/index.ts
  src/commands/profile/set.ts
  src/commands/shop/buy.ts
  src/commands/shop/create.ts
  src/commands/shop/delete.ts
  src/commands/shop/index.ts
  src/commands/shop/list.ts
  src/commands/tags/create.ts
  src/commands/tags/delete.ts
  src/commands/tags/index.ts
  src/commands/tags/list.ts
  src/commands/tags/raw.ts
  src/components/help.ts
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/index.ts
  src/types/applicationCommand.ts
  src/types/event.ts
  src/util/files.ts
  tsconfig.json
Labels: refactor, semver-patch

#147 enforce using braces (scopes) for blocks
  .eslintrc.json
  src/classes/handlers/CommandHandler.ts
  src/classes/handlers/TagHandler.ts
  src/cmds/ban.ts
  src/cmds/bedwars.ts
  src/cmds/case.ts
  src/cmds/dev.ts
  src/cmds/howgay.ts
  src/cmds/kick.ts
  src/cmds/mute.ts
  src/cmds/skywars.ts
  src/cmds/unmute.ts
  src/cmds/warn.ts
  src/commands/ban.ts
  src/commands/bedwars.ts
  src/commands/case.ts
  src/commands/deploy/create.ts
  src/commands/deploy/delete.ts
  src/commands/dev/reload.ts
  src/commands/kick.ts
  src/commands/listcase.ts
  src/commands/rob.ts
  src/commands/shop/create.ts
  src/commands/skywars.ts
  src/commands/tags/create.ts
  src/commands/tags/delete.ts
  src/commands/tags/list.ts
  src/commands/tags/raw.ts
  src/commands/timeout.ts
  src/commands/warn.ts
  src/components/listcase.ts
  src/context/listcase.ts
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/messageDelete.ts
  src/events/messageUpdate.ts
  src/util/modLog.ts
Labels: ci

#150 issue forms
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: chore, semver-patch
