Repository Fluorinebot/fluorine, pull requests merged in 2023-03, with the labels that each got.

#397 small cleanup
  .eslintrc.json
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
  .prettierignore
  .prettierrc.json
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  assets/url.txt
  assets/users.txt
  assets/words.txt
  i18n/en-US/responses.json
  package-lock.json
  package.json
  src/api/guilds/[id]/cases/index.ts
  src/classes/Client.ts
  src/classes/modules/OAuthModule.ts
  src/env/index.ts
  src/index.ts
  src/types/hypixel.ts
  tsconfig.json
Labels: chore, refactor, dependencies

#398 docker compose
  .gitignore
  Dockerfile
  docker-compose.yml
  src/classes/builders/bases/BaseApplicationCommandBuilder.ts
  src/classes/builders/bases/BaseComponentBuilder.ts
  src/classes/builders/bases/index.ts
Labels: chore

#400 bump neon-env to 0.2.0
  package-lock.json
  package.json
  src/env/index.ts
Labels: dependencies
